# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Proper Digital
email: hello@properdigital.co
description: > # this means to ignore newlines until "baseurl:"
  Web design and development services, branding packages, and continuous support offered.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://properdigital.co" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown

exclude: [node_modules/, .gitignore, gulpfile.js, package.json, jekyll]
